FILE_LOADER_PROGRAM_START   =$02a7
FILE_LOADER_FILENAME_LENGTH =$340
FILE_LOADER_FILENAME        =$341


SPRITE_MENU_PROGRAM_START         =$a100
SPRITE_MENU_FIND_ARRAY_ENTRY      =$a2c7
SPRITE_MENU_FIND_MENU_CHOICES     =$a312

SPRITE_MENU_MENU_COUNT            =$3fe
SPRITE_MENU_MENU_INDEX            =$3ff
SPRITE_MENU_STRING_FOUND_ADDRESS  =$4
SPRITE_MENU_STRING_FOUND_LENGTH   =$3



QUAD_MENU_PROGRAM_START     =$c7a0


DRAW_TILE_LOAD_START        =$A800
DRAW_TILE_BOARD_X           =DRAW_TILE_LOAD_START+0
DRAW_TILE_BOARD_Y           =DRAW_TILE_LOAD_START+1

DRAW_TILE_PROGRAM_START     =DRAW_TILE_LOAD_START+2
